const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
$('#menuToggle').addEventListener('click',()=>$('#mobileMenu').classList.toggle('open'));
$$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>$('#mobileMenu').classList.remove('open')));
const modal=$('#rdvModal'), content=$('#rdvContent');let state={step:1,motif:null,day:null,time:null,name:'',discord:'',phone:'',email:'',details:''};
const motifs=[['Demande de financement','Soutien financier pour un projet ou une entreprise.'],['Entretien avec le Gouverneur','Rencontre officielle avec le Gouverneur.'],['Entretien avec le Vice-Gouverneur','Rencontre officielle avec le Vice-Gouverneur.'],['Rencontre avec le Chef de Cabinet','Suivi de dossier auprès du Cabinet.'],['Dépôt de dossier','Remise d’un dossier administratif complet.'],['Réclamation','Signalement ou contestation d’une décision.'],['Projet gouvernemental','Présentation d’un projet à valider.'],['Autre','Toute autre demande non listée ci-dessus.']];
const days=['Mar 6 oct.','Mer 7 oct.','Jeu 8 oct.','Ven 9 oct.','Sam 10 oct.'];const times=['20:00','20:15','20:30','20:45','21:00','21:15','21:30','21:45','22:00','22:15','22:30','22:45','23:00','23:15','23:30'];
function openRdv(){state={step:1,motif:null,day:null,time:null,name:'',discord:'',phone:'',email:'',details:''};modal.classList.add('open');modal.setAttribute('aria-hidden','false');render()}
function closeRdv(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
$$('[data-open-rdv]').forEach(b=>b.addEventListener('click',openRdv));$('#modalClose').addEventListener('click',closeRdv);modal.addEventListener('click',e=>{if(e.target===modal)closeRdv()});
function render(){updateSteps();let html='';if(state.step===1){html=`<h2 class="rdv-title">1. Choisissez un motif</h2><div class="motifs">${motifs.map((m,i)=>`<button class="motif" data-m="${i}"><b>${m[0]}</b><span>${m[1]}</span></button>`).join('')}</div>`}else if(state.step===2){html=`<h2 class="rdv-title">2. Choisissez un créneau</h2><div class="days">${days.map(d=>`<button class="day ${state.day===d?'selected':''}" data-day="${d}">${d}</button>`).join('')}</div><div style="height:25px"></div><div class="times">${times.map(t=>`<button class="time ${state.time===t?'selected':''}" data-time="${t}">${t}</button>`).join('')}</div><div class="rdv-actions"><button class="back-btn" data-back>Retour</button><button class="gold-btn" data-next>Continuer</button></div>`}else if(state.step===3){html=`<div class="summary"><h2 class="rdv-title">3. Vos informations</h2><p><b>${state.motif}</b> · ${state.day} à ${state.time}</p></div><div class="form-grid"><label class="field">Nom du personnage<input id="name" value="${state.name}" placeholder="Prénom Nom"></label><label class="field">Identifiant Discord<input id="discord" value="${state.discord}" placeholder="pseudo#0000"></label><label class="field">Téléphone (RP)<input id="phone" value="${state.phone}" placeholder="555-0100"></label><label class="field">Email de contact<input id="email" type="email" value="${state.email}" placeholder="contact@lossantos.gov"></label><label class="field full">Précisions complémentaires<textarea id="details" placeholder="Détaillez brièvement l'objet de votre demande...">${state.details}</textarea></label></div><div class="rdv-actions"><button class="back-btn" data-back>Retour</button><button class="gold-btn" data-confirm>Confirmer le rendez-vous</button></div>`}else{html=`<div style="text-align:center;padding:40px 10px"><div class="circle" style="margin:auto">✓</div><h2 class="rdv-title">Rendez-vous confirmé</h2><p>Votre demande a bien été enregistrée.</p><p><b>${state.motif}</b><br>${state.day} à ${state.time}</p><button class="gold-btn" data-close>Fermer</button></div>`}content.innerHTML=html;$$('[data-m]').forEach(b=>b.onclick=()=>{state.motif=motifs[+b.dataset.m][0];state.step=2;render()});$$('[data-day]').forEach(b=>b.onclick=()=>{state.day=b.dataset.day;render()});$$('[data-time]').forEach(b=>b.onclick=()=>{state.time=b.dataset.time;render()});$$('[data-back]').forEach(b=>b.onclick=()=>{state.step--;render()});$$('[data-next]').forEach(b=>b.onclick=()=>{if(!state.day||!state.time)return showToast('Choisissez une date et une heure.');state.step=3;render()});$$('[data-confirm]').forEach(b=>b.onclick=confirmRdv);$$('[data-close]').forEach(b=>b.onclick=closeRdv)}
function updateSteps(){['s2','s3','s4'].forEach((id,i)=>{const el=$('#'+id);el.classList.toggle('current',state.step===i+2);el.classList.toggle('done',state.step>i+2)});document.querySelector('.steps .step').classList.toggle('current',state.step===1)}
function confirmRdv(){state.name=$('#name').value.trim();state.discord=$('#discord').value.trim();state.phone=$('#phone').value.trim();state.email=$('#email').value.trim();state.details=$('#details').value.trim();if(!state.name||!state.email)return showToast('Veuillez remplir votre nom et votre email.');state.step=4;render()}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
$('#discordLink').addEventListener('click',e=>{e.preventDefault();showToast('Ajoutez ici le lien de votre serveur Discord.')});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeRdv()});
